name             'jpetstore'
maintainer       'Charles Johnson'
maintainer_email 'charles@opsocde.com'
license          'Apache 2.0'
description      'Installs/configures jpetstore'
version          '0.5.0'
recipe           'jpetstore::install', 'Installs jpetstore dependencies'
recipe			 'jpetstore::create', 'Creates jpetstore instance'

depends 'tcserver'
depends 'mysql', '~> 5.0.2'
depends 'mysql-chef_gem'
depends 'database', '~> 2.1.2'
depends 'simple_iptables'
